import { describe, expect, it } from 'vitest';
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';
import { area } from '$lib/core/prototype/area/definition.server.js';
import { collection } from '$lib/core/prototype/collection/definition.server.js';
import { describePipeline } from './build-pipeline.server.js';

/**
 * The pipeline, written down — every hook, what it declares, and who put it there.
 *
 * A resolved pipeline is computed from marks, never from a list: a hook says what state it needs
 * (`requires`) and what it leaves behind (`provides`), and `resolvePipeline` sorts. That is what
 * lets a feature add hooks without any prototype naming it. It is also why the thing is hard to
 * read — the order exists nowhere in the source, and a wrong mark reorders it silently.
 *
 * So this renders it, and pins it: the table lives in `docs/pipeline-map.md` and this asserts the
 * file matches. Regenerate with
 *
 *     bun run rime:pipeline
 *
 * A pipeline change therefore shows up as a **diff in a readable document** rather than only as a
 * changed array in `pipeline-order.spec.ts`. That spec is still the guard on the orderings that
 * matter and says why each one matters; this is the map.
 */

const MAP = path.resolve(process.cwd(), 'docs/pipeline-map.md');

/** One representative config per shape a pipeline actually takes. */
const CASES: { label: string; note: string; definition: any; config: any }[] = [
  {
    label: 'a plain collection',
    note: 'No feature contributes a write hook, so `beforeUpdate` is the prototype’s own steps and nothing else.',
    definition: collection,
    config: { type: 'collection', slug: 'pages' }
  },
  {
    label: 'a versioned collection',
    note: 'The three `versions` hooks appear by the feature being enabled. `handleNewVersion` sits between `resolveContentOwner` (whose default it overrides) and `buildDataConfigMap` (because it reads the submission as sent) — both edges declared, neither written down.',
    definition: collection,
    config: { type: 'collection', slug: 'news', versions: { draft: true } }
  },
  {
    label: 'an auth collection',
    note: '`removePrivateFields` leads every read; `augmentFieldsPassword` must land after the blank merge on create and may run earlier on update, from one declaration — see `blank-merged`.',
    definition: collection,
    config: { type: 'collection', slug: 'staff', auth: true }
  },
  {
    label: 'an upload collection, nested, with a url',
    note: '`populateURL` runs after `setDocumentTitle` because it requires `title` — the one read edge a wrong mark would silently invert.',
    definition: collection,
    config: {
      type: 'collection',
      slug: 'medias',
      upload: { directories: true },
      nested: true,
      $url: () => '/x'
    }
  },
  {
    label: 'an area, versioned',
    note: 'No create and no delete: a second row is not a thing.',
    definition: area,
    config: { type: 'area', slug: 'settings', versions: { draft: true } }
  }
];

const cell = (values: string[]) => (values.length ? values.map((v) => `\`${v}\``).join(' ') : '—');

const render = () => {
  const lines = [
    '# The resolved pipeline, per config shape',
    '',
    '<!-- Generated by `bun run rime:pipeline`. Do not edit by hand — `pipeline-map.spec.ts` fails if this file and the code disagree. -->',
    '',
    'Each table is the order a real config resolves to. **from** is who contributed the hook: the',
    'prototype itself, a feature by name, or the author’s `$hooks`. **requires** / **provides** are',
    'the marks the resolver sorted by — a hook runs after every active hook providing each mark it',
    'requires, and a mark nothing active provides is satisfied vacuously.',
    '',
    'Removing a feature removes exactly the rows naming it. That is the test to apply when asking',
    'whether a feature is decoupled: if a hook of its shows up under `collection` or `area`, the',
    'prototype is listing it by hand and deleting the feature would break the prototype.',
    ''
  ];

  for (const { label, note, definition, config } of CASES) {
    lines.push(`## ${label}`, '', note, '');

    for (const [timing, hooks] of Object.entries(describePipeline(definition, config))) {
      if (!hooks.length) continue;
      lines.push(
        `### ${timing}`,
        '',
        '| # | hook | from | requires | provides |',
        '| - | ---- | ---- | -------- | -------- |'
      );
      hooks.forEach((hook, index) => {
        lines.push(
          `| ${index + 1} | \`${hook.name}\` | ${hook.from} | ${cell(hook.requires)} | ${cell(hook.provides)} |`
        );
      });
      lines.push('');
    }
  }

  return lines.join('\n');
};

describe('the pipeline map', () => {
  it('matches docs/pipeline-map.md', () => {
    const rendered = render();

    if (process.env.RIME_WRITE_PIPELINE_MAP) {
      writeFileSync(MAP, rendered);
      expect(rendered).toContain('| # | hook | from | requires | provides |');
      return;
    }

    // Failing here means a hook, a mark or a feature's hook list changed. Read the diff — it is
    // the pipeline — then `bun run rime:pipeline` to accept it.
    expect(readFileSync(MAP, 'utf-8')).toBe(rendered);
  });

  it('has every hook attributed', () => {
    // `describePipeline` matches hooks to contributors by identity. A `?` means the resolver
    // returned something none of the three input lists contains, which would mean the composition
    // and the description have drifted apart.
    for (const { definition, config } of CASES) {
      for (const hooks of Object.values(describePipeline(definition, config))) {
        expect(hooks.map((hook) => hook.from)).not.toContain('?');
      }
    }
  });
});
